
services:
  - type: web
    name: fastapi-on-render
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 127.0.0.1 --port $PORT=5000
    # Optional health check endpoint
    healthCheckPath: /healthz
