services:
  - type: web
    name: fastapi-on-render
    runtime: python
    plan: free

    # Ensure a deterministic Python environment
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONUNBUFFERED
        value: "1"

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: >
      uvicorn main:app
      --host 127.0.0.1
      --port 5000
      --proxy-headers
      --forwarded-allow-ips="*"

    healthCheckPath: /healthz




# services:
#   - type: web
#     name: fastapi-on-render
#     runtime: python
#     plan: free
#     buildCommand: pip install -r requirements.txt
#     startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
#     # Optional health check endpoint
#     healthCheckPath: /healthz


